## TF Function

In [2]:
import tensorflow as tf
import numpy as np
import tensorflow.keras as K
import pandas as pd
import matplotlib.pyplot as plt

## Defining a regular Python function

In [3]:
def cube(x):
    return x ** 3

In [4]:
cube(2)

8

In [5]:
cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

## Wrapping the function as TF F

In [6]:
tf_cube = tf.function(cube)

In [7]:
tf_cube(2)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [8]:
tf_cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [9]:
tf_cube(tf.constant([10, 20]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1000, 8000], dtype=int32)>

In [10]:
tf.autograph.to_code(tf_cube.python_function)

"def tf__cube(x):\n    with ag__.FunctionScope('cube', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:\n        do_return = False\n        retval_ = ag__.UndefinedReturnValue()\n        try:\n            do_return = True\n            retval_ = ag__.ld(x) ** 3\n        except:\n            do_return = False\n            raise\n        return fscope.ret(retval_, do_return)\n"